# remember that we need a NodePort for node js app too
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: monitoring
  labels:
    name: result-service
    app: cka-ckad-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: result-app-result-pod
    app: cka-ckad-voting-app