apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    app: cka-ckad-voting-app
    type: local
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: data
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: cka-ckad-voting-app
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvClaim.storageClass | quote }}