# for running in docker compose with prebuilt images

# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: elkakimmie/voting_app:latest
    depends_on:
      redis:
        condition: service_healthy 
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: elkakimmie/voting_app_result:latest
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: elkakimmie/voting_app_worker:latest
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
