apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: annt
  name: annt
  annotations:
    author: colossus
    project: 'Study Group'
spec:
  containers:
  - image: nginx
    name: annt
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
