apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ckad
  name: ckad
spec:
  containers:
  - image: ubuntu/apache2
    name: ckad
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
