apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bboxcmdedit
  name: bboxcmdedit
spec:
  containers:
  - args:
    - C:/Program Files/Git/usr/bin/sh
    - -c
    - date
    image: busybox
    name: bboxcmdedit
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
