apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: test
    tier: backend
  name: label
spec:
  containers:
  - image: alpine
    name: label
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
