apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: monitoring
  labels:
    name: redis-service
    app: cka-ckad-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: cka-ckad-voting-app
