apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: monitoring
  labels:
    name: db-service
    app: cka-ckad-voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: cka-ckad-voting-app
