apiVersion: v1
kind: Pod
metadata:
  name: result-app-result-pod
  namespace: monitoring
  labels:
    name: result-app-result-pod
    app: cka-ckad-voting-app
spec:
  containers:
  - name: result-app
    image: elkakimmie/voting_app_result:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
