apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: cka-ckad-voting-app
spec:
  containers:
  - name: worker-app
    image: elkakimmie/voting_app_worker:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    # remove the port section

