apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: cka-ckad-voting-app
    name: db-service
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: cka-ckad-voting-app
    name: postgres-pod
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.db.ports | toYaml | nindent 2 -}}