apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: monitoring
  labels:
    name: redis-deploy
    app: cka-ckad-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: cka-ckad-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: cka-ckad-voting-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        # default port of redis image
          - containerPort: 6379
