apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limited
  name: limited
  namespace: tampa
spec:
  containers:
  - image: bitnami/nginx
    name: limited
    resources:
      requests:
        memory: "30Mi"
        cpu: "25m"
      limits:
        memory: "300Mi"
        cpu: "300m"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
