apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - image: nginx
    name: main
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared
  - image: nginx
    name: helper
    args: [/bin/sh, -c, 'tail -n+1 -f /var/log/nginx/access.log']
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
