apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: user
spec:
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: i-need
  containers:
  - image: nginx
    name: user
    volumeMounts:
    - mountPath: "usr/share/nginx"
      name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
