apiVersion: v1
kind: PersistentVolume
metadata:
  name: sg-pv
  labels:
    type: local
spec:
  storageClassName: sg-rocking
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shared"
