apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "dbSecret.postgresPassword is required" .Values.dbSecret.postgresPassword
    | b64enc | quote }}