apiVersion: v1
kind: Pod
metadata:
  name: crud
  labels:
    app: crud
spec:
  containers:
  - name: crud
    imagePullPolicy: Always
    image: gulcantopcu/ckad-crud:latest
    resources:
      requests:
        memory: "21Mi"
        cpu: "2m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 5000
    env:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: MYSQL_PASSWORD
    - name: MYSQL_DB
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_DATABASE
    - name: MYSQL_PORT
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_PORT
    - name: MYSQL_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: crud-svc
spec:
  selector:
    app: crud
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000