apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin
    name: phpadmin-pod
    env:
    - name: PMA_HOST
      valueFrom:
        configMapKeyRef:
          name: phpadmin-config
          key: PMA_HOST
    - name: PMA_PORT
      valueFrom:
        configMapKeyRef:
          name: phpadmin-config
          key: PMA_PORT
    - name: PMA_USER
      valueFrom:
        secretKeyRef:
          name: phpadmin-secret
          key: PMA_USER
    - name: PMA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: phpadmin-secret
          key: PMA_PASSWORD
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

